---
output: github_document
always_allow_html: true
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# mTools

<!-- badges: start -->
<!-- badges: end -->

mTools a collection of function I regularly use.

## Installation

You can install the development version of mTools from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("m-mburu/mTools")
```
## load package

```{r}
library(mTools)
```

## Example

This is a basic example which shows you how to solve a common problem:

```{r example, eval=FALSE}

iris_head  <- head(iris)
data_table(iris_head)
```

## Produce nice Rmarkdowns tables from model objects

### Tidy summary results

```{r}
library(MASS)
data(anorexia)

anorex.1 <- glm(Postwt ~ Prewt + Treat + offset(Prewt),
                family = gaussian, data = anorexia)

library(knitr)
library(broom)
DT_tidy_model(anorex.1, output_function = "kable")
```

### Tidy glance results

```{r}
DT_tidy_model(anorex.1,
              tidy_function ="glance" ,
              output_function = "kable")
```

