---
title: "flat_minimal.Rmd empty"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r development, include=FALSE}
library(testthat)
```

<!--
You need to run the 'description' chunk in the '0-dev_history.Rmd' file before continuing your code there.
-->

```{r development-load}
# Load already included functions if relevant
pkgload::load_all(export_all = FALSE)
```

# data_table

```{r function-data_table}
#' Title Custom function for datatables 
#' 
#' Description A function to produce beautiful tables 
#' 
#' @return a an object of class DT
#' @param df A data frame 
#' @param pageLength An integer, number of rows displayed
#' @importFrom DT datatable
#' @export
#' @return Object of class DT
data_table <- function(df, pageLength = 50){
  n_col = ncol(df)-1
  datatable(df,
            rownames = FALSE,
            style = "bootstrap4", class = 'cell-border stripe',
            options = list(scrollX = TRUE,
                           pageLength = pageLength,
                           columnDefs = list(list(className = 'dt-center', targets = 0:n_col))
            )
  )
}


```


```{r example-data_table}
iris_head  <- head(iris)
data_table(iris_head)
```


```{r tests-data_table}
test_that("data_table works", {
  expect_true(inherits(data_table, "function")) 
})
```

# create_save_workbook 

```{r function-create_save_workbook }
#' Title
#' 
#' Description

#' @param list_of_dfs A list of data frames to write to the workbook.
#' @param path_name The path to the Excel workbook to create.
#' @param sheet_names A character vector of names for the sheets in the workbook.
#'
#' @return The workbook object.
#'
#' @importFrom openxlsx createWorkbook addWorksheet writeData saveWorkbook
#' @importFrom data.table setDF
#'
#' @examples
#' @export
create_save_workbook  <- function(list_of_dfs, path_name, sheet_names) {
  
  # Check the input arguments for validity
  stopifnot(is.list(list_of_dfs) && all(sapply(list_of_dfs, is.data.frame)))
  stopifnot(is.character(sheet_names))
  stopifnot("Directory provided does not exists"= dir.exists(dirname(path_name)))
  stopifnot("Number of sheets is not equal to number of data frames"= length(list_of_dfs) ==length(sheet_names))
  # Create the workbook
  
  wb <- createWorkbook()
  
  # Write the data frames to the workbook
  lapply(seq_along(list_of_dfs), function(i) {
    df <- list_of_dfs[[i]]
    sheet_i <- sheet_names[i]
    setDF(df)
    addWorksheet(wb, sheet_i)
    writeData(wb, sheet_i, df, startCol = 1, startRow = 1)
  })
  
  # Save the workbook
  saveWorkbook(wb, file = path_name)
  
  # Return the workbook object
  invisible(wb)
}
```




```{r example-create_save_workbook }
df1 <- data.frame(x = 1:10, y = 11:20)
df2 <- data.frame(a = letters[1:5], b = letters[6:10])
list_of_dfs <- list(df1, df2)

# Specify the names of the sheets
sheet_names <- c("Sheet1", "Sheet2")

#create temporary folder 
path_name <- tempfile(pattern = "create_work_book") |>
  normalizePath(winslash = "/")

dir.create(path_name)

# create file name
file_name <- file.path(path_name, "test.xlsx")

# Create the workbook
create_save_workbook(list_of_dfs,
                     path_name = file_name, 
                     sheet_names)
file.remove(file_name)
unlink(path_name)
```



```{r tests-create_save_workbook }
test_that("create_save_workbook() creates a workbook with the specified sheets", {
  
  
  # Create a list of data frames
  df1 <- data.frame(x = 1:10, y = 11:20)
  df2 <- data.frame(a = letters[1:5], b = letters[6:10])
  list_of_dfs <- list(df1, df2)
  
  # Specify the names of the sheets
  sheet_names <- c("Sheet1", "Sheet2")
  
  # Create the workbook
  #create temporary folder 
  path_name <- tempfile(pattern = "create_work_book") |>
    normalizePath(winslash = "/")
  
  dir.create(path_name)
  
  # create file name
  path_name <- file.path(path_name, "test.xlsx")
  
  create_save_workbook(list_of_dfs, 
                       path_name ,
                       sheet_names)
  
  expect_error( create_save_workbook(list_of_dfs, path_name="some/path/name" , sheet_names),
                regexp = "Directory provided does not exists" )
  
  expect_error( create_save_workbook(list_of_dfs, path_name , sheet_names[1]),
                regexp = "Number of sheets is not equal to number of data frames" )
  # Check that the workbook exists

  
  expect_true(file.exists(path_name))
  
  # Open the workbook and check that the sheets have the correct data
  library(openxlsx)
  wb <- loadWorkbook(path_name)
  expect_equal(read.xlsx(wb, "Sheet1"), df1)
  expect_equal(read.xlsx(wb, "Sheet2"), df2)
})
```


# collapse_vec

```{r function-collapse_vec}
#' Title  Collapse a vector into a string, separated by a pipe character (|).
#' 
#' Description  Collapse a vector into a string, separated by a pipe character (|).
#' 
#' @param x A vector.
#' @param separator_char A character vector eg -, | use as a separator
#' @importFrom stringr str_trim
#' @return A string.
#'
#' @export


collapse_vec <- function(x, separator_char =  NULL ) {
  if(is.null(separator_char)){
    
    separator_char = "|"
  }
  x |>
    str_trim() |>
    paste0(collapse = separator_char )
} 

```


```{r example-collapse_vec}
x <- c("a", "b", "c")
collapse_vec(x)
```


```{r tests-collapse_vec}
library(testthat)

test_that("collapse_vec() collapses a vector into a string, separated by a pipe character (|)", {
  # Create a vector
  x <- c("a", "b", "c")
  
  # Check the output
  expect_equal(collapse_vec(x), "a|b|c")
})

test_that("collapse_vec() returns a string", {
  # Create a vector
  x <- c("a", "b", "c")
  
  # Check the output type
  expect_is(collapse_vec(x), "character")
})

test_that("collapse_vec() works with empty vectors", {
  # Create an empty vector
  x <- c()
  
  # Check the output
  expect_equal(collapse_vec(x), "")
})
```

# round_all_num_cols
    
```{r function-round_all_num_cols}
#' Title Round all numeric columns to specified digits
#'
#' Description A function to round all numeric columns of a data frame
#'
#' @param df A data frame
#' @importFrom data.table setDT
#' @param round_digits  The number of digits to round to
#'
#' @return A data frame with all numeric columns rounded to the specified number of digits
#'
#' @export
round_all_num_cols <- function(df, round_digits = 2) {

  # Convert the data frame to a data.table
  setDT(df)

  # Get the names of the numeric columns
  num_cols <- df[, .SD, .SDcols = is.numeric] %>%
    names()

  # Round the numeric columns to the specified number of digits
  df[, (num_cols) := lapply(.SD, round, digits = round_digits), .SDcols = num_cols]

  # Return the data.table
  df
}
```
  
```{r example-round_all_num_cols}
round_all_num_cols(iris) %>%
  head()
```
  
```{r tests-round_all_num_cols}
test_that("round_all_num_cols works", {
  expect_true(inherits(round_all_num_cols, "function")) 
})
```
  
  
# combine_conf_intervals
    
```{r function-combine_conf_intervals}
#' Create a string with CI given estimate and confidence interval
#' Combines a point estimate, lower bound, and upper bound into a string in the format
#' @param estimate The point estimate.
#' @param lower The lower bound of the confidence interval.
#' @param upper The upper bound of the confidence interval.
#'
#' @return A string in this format  `estimate [lower upper]`.
#' 
#' @export
combine_conf_intervals <- function(estimate, lower, upper){
  
  
  y =  paste0(estimate, "[", lower,  " ", upper, "]")
  y
    
}
```
  
```{r example-combine_conf_intervals}

combine_conf_intervals(0.5, 0.4, 0.6)

```
  
```{r tests-combine_conf_intervals}
test_that("combine_conf_intervals works", {
  expect_true(inherits(combine_conf_intervals, "function")) 
})
```
  
# DT_tidy_model
    
```{r function-DT_tidy_model}
#' Title  Produce a nice data table from tidy model object
#' Description This function takes a tidy model object and converts it into a formatted data table. It can use custome function eg knitr kable
#' @param model The tidy model object.
#' @param round_digts An integer specifying the number of digits to round the numeric columns. Default is 4.
#' @param output_function A string specifying the output function to use. Default is "data_table".
#' @param tidy_function a function that returns tibble, data frame from a model object eg tidy, glance functions from broom 
#' @param coefficient_name  The name of the column with coeffcients 
#' @param coefficient_name_new  In case you want a custom name for your coefficient eg ODDS Ratio 95%CI
#' @param exp_estimate in case you have logistic regression and you want odds ratio 
#' @param confint_level Confidence level to be used 
#' @param coefficient_ci whether to add coefficent CI
#' @importFrom broom tidy
#' @importFrom stats confint coef
#' @importFrom data.table setDT setnames
#'
#' @return An object of class output_function, ie kable, DT etc representing the formatted data table.
#'
#' @export
DT_tidy_model <- function(model, round_digts = 4,
                          tidy_function = "tidy", 
                          output_function = "data_table", 
                          coefficient_name = "estimate",
                          coefficient_name_new = NULL,
                          exp_estimate = FALSE, 
                          coefficient_ci = FALSE,
                          confint_level = .95) {
  
  # Get the tidy model object
  tidy_function_matched  =  match.fun(tidy_function)
  tidy_model <- tidy_function_matched(model)
  
  # Convert the tidy model object to a data.table
  setDT(tidy_model)
  
  if(coefficient_ci){
    
    nms_cv = c("lower", "upper")
    
    tidy_model[,(nms_cv) :=  as.data.frame(confint(model, level = confint_level))]
  }
  
  
  
  
  if(exp_estimate){
    
    tidy_model[,  (coefficient_name) := exp(coef(model))]
    
    if(coefficient_ci){
      tidy_model[, (nms_cv) := lapply(.SD, exp), .SDcols = nms_cv]
    }
  }
  # Get the names of the numeric columns
  num_nms <- tidy_model[, .SD, .SDcols = is.numeric] |>
    names()
  
  # Round the numeric columns to the specified number of digits
  round_all_num_cols(tidy_model, round_digits = round_digts)
  
  if(coefficient_ci){
    
    tidy_model[, (coefficient_name)  := combine_conf_intervals(get(coefficient_name), lower, upper)]
    tidy_model[, (nms_cv) := NULL]
  }
  if(!is.null(coefficient_name_new)){
    
    stopifnot("coefficient_name_new must be a string" = is.character(coefficient_name_new))
    
    setnames(tidy_model,
             coefficient_name, 
             coefficient_name_new )
  }
  # Return the data.table
  output_function_matched  =  match.fun(output_function)
  
  output_function_matched(tidy_model)
}

```
  
```{r example-DT_tidy_model}
## model from glm examples
data("diabetes")
library(MASS)
library(knitr)
library(broom)
model <- glm(Outcome ~ .,
             family = binomial(),
             data = diabetes)


DT_tidy_model(model, round_digts = 4,
              tidy_function = "tidy", 
              output_function = "kable", 
              coefficient_name = "estimate",
              coefficient_name_new = "ODDS Ratio 95% CI",
              exp_estimate = TRUE, 
              coefficient_ci= TRUE,
              confint_level = .95)
```
  
```{r tests-DT_tidy_model}
test_that("DT_tidy_model works", {
  expect_true(inherits(DT_tidy_model, "function")) 
})
```
  

```{r development-inflate, eval=FALSE}
# Run but keep eval=FALSE to avoid infinite loop
# Execute in the console directly
fusen::inflate(flat_file = "dev/flat_minimal.Rmd", 
               vignette_name = "Minimal")
```
