# WARNING - Generated by {fusen} from /dev/flat_minimal.Rmd: do not edit by hand

library(testthat)

test_that("collapse_vec() collapses a vector into a string, separated by a pipe character (|)", {
  # Create a vector
  x <- c("a", "b", "c")
  
  # Check the output
  expect_equal(collapse_vec(x), "a|b|c")
})

test_that("collapse_vec() returns a string", {
  # Create a vector
  x <- c("a", "b", "c")
  
  # Check the output type
  expect_is(collapse_vec(x), "character")
})

test_that("collapse_vec() works with empty vectors", {
  # Create an empty vector
  x <- c()
  
  # Check the output
  expect_equal(collapse_vec(x), "")
})
