# WARNING - Generated by {fusen} from /dev/flat_minimal.Rmd: do not edit by hand

test_that("create_save_workbook() creates a workbook with the specified sheets", {
  
  
  # Create a list of data frames
  df1 <- data.frame(x = 1:10, y = 11:20)
  df2 <- data.frame(a = letters[1:5], b = letters[6:10])
  list_of_dfs <- list(df1, df2)
  
  # Specify the names of the sheets
  sheet_names <- c("Sheet1", "Sheet2")
  
  # Create the workbook
  path_name = file.path("inst", "extdata", "test.xlsx" )
  file.remove(path_name)
  create_save_workbook(list_of_dfs, path_name , sheet_names)
  
  expect_error( create_save_workbook(list_of_dfs, path_name="some/path/name" , sheet_names),
                regexp = "Directory provided does not exists" )
  
  expect_error( create_save_workbook(list_of_dfs, path_name , sheet_names[1]),
                regexp = "Number of sheets is not equal to number of data frames" )
  # Check that the workbook exists
  path_name <- system.file("extdata",
                           "test.xlsx",
                           package = "mTools")
  
  expect_true(file.exists(path_name))
  
  # Open the workbook and check that the sheets have the correct data
  library(openxlsx)
  wb <- loadWorkbook(path_name)
  expect_equal(read.xlsx(wb, "Sheet1"), df1)
  expect_equal(read.xlsx(wb, "Sheet2"), df2)
})
