# WARNING - Generated by {fusen} from /dev/flat_minimal.Rmd: do not edit by hand

#' Title  Collapse a vector into a string, separated by a pipe character (|).
#' 
#' Description  Collapse a vector into a string, separated by a pipe character (|).
#' 
#' @param x A vector.
#' @param separator_char A character vector eg -, | use as a separator
#' @importFrom stringr str_trim
#' @return A string.
#'
#' @export


#' @examples
#' x <- c("a", "b", "c")
#' collapse_vec(x)
collapse_vec <- function(x, separator_char =  NULL ) {
  if(is.null(separator_char)){
    
    separator_char = "|"
  }
  x |>
    str_trim() |>
    paste0(collapse = separator_char )
} 

