# WARNING - Generated by {fusen} from /dev/flat_minimal.Rmd: do not edit by hand

#' Title  Collapse a vector into a string, separated by a pipe character (|).
#' 
#' Description  Collapse a vector into a string, separated by a pipe character (|).
#' 
#' @param x A vector.
#' @importFrom stringr str_trim
#' @return A string.
#'
#' @export


#' @examples
#' x <- c("a", "b", "c")
#' collapse_vec(x)
collapse_vec <- function(x) {
  x |>
    str_trim() |>
    paste0(collapse = "|")
} 

