# WARNING - Generated by {fusen} from /dev/flat_minimal.Rmd: do not edit by hand

#' Create a string with CI given estimate and confidence interval
#' Combines a point estimate, lower bound, and upper bound into a string in the format
#' @param estimate The point estimate.
#' @param lower The lower bound of the confidence interval.
#' @param upper The upper bound of the confidence interval.
#'
#' @return A string in this format  `estimate [lower upper]`.
#' 
#' @export
#' @examples
#' 
#' combine_conf_intervals(0.5, 0.4, 0.6)
#' 
combine_conf_intervals <- function(estimate, lower, upper){
  
  
  y =  paste0(estimate, "[", lower,  " ", upper, "]")
  y
    
}
