# WARNING - Generated by {fusen} from /dev/flat_minimal.Rmd: do not edit by hand

#' Title
#' 
#' Description

#' @param list_of_dfs A list of data frames to write to the workbook.
#' @param path_name The path to the Excel workbook to create.
#' @param sheet_names A character vector of names for the sheets in the workbook.
#'
#' @return The workbook object.
#'
#' @importFrom openxlsx createWorkbook addWorksheet writeData saveWorkbook
#' @importFrom data.table setDF
#'
#' @examples
#' df1 <- data.frame(x = 1:10, y = 11:20)
#' df2 <- data.frame(a = letters[1:5], b = letters[6:10])
#' list_of_dfs <- list(df1, df2)
#' 
#' # Specify the names of the sheets
#' sheet_names <- c("Sheet1", "Sheet2")
#' 
#' #create temporary folder 
#' path_name <- tempfile(pattern = "create_work_book") |>
#'   normalizePath(winslash = "/")
#' 
#' dir.create(path_name)
#' 
#' # create file name
#' file_name <- file.path(path_name, "test.xlsx")
#' 
#' # Create the workbook
#' create_save_workbook(list_of_dfs,
#'                      path_name = file_name, 
#'                      sheet_names)
#' file.remove(file_name)
#' unlink(path_name)
#' @export
create_save_workbook  <- function(list_of_dfs, path_name, sheet_names) {
  
  # Check the input arguments for validity
  stopifnot(is.list(list_of_dfs) && all(sapply(list_of_dfs, is.data.frame)))
  stopifnot(is.character(sheet_names))
  stopifnot("Directory provided does not exists"= dir.exists(dirname(path_name)))
  stopifnot("Number of sheets is not equal to number of data frames"= length(list_of_dfs) ==length(sheet_names))
  # Create the workbook
  
  wb <- createWorkbook()
  
  # Write the data frames to the workbook
  lapply(seq_along(list_of_dfs), function(i) {
    df <- list_of_dfs[[i]]
    sheet_i <- sheet_names[i]
    setDF(df)
    addWorksheet(wb, sheet_i)
    writeData(wb, sheet_i, df, startCol = 1, startRow = 1)
  })
  
  # Save the workbook
  saveWorkbook(wb, file = path_name)
  
  # Return the workbook object
  invisible(wb)
}
