# WARNING - Generated by {fusen} from /dev/flat_minimal.Rmd: do not edit by hand

#' Title Round all numeric columns to specified digits
#'
#' Description A function to round all numeric columns of a data frame
#'
#' @param df A data frame
#' @importFrom data.table setDT
#' @param round_digits  The number of digits to round to
#'
#' @return A data frame with all numeric columns rounded to the specified number of digits
#'
#' @export
#' @examples
#' round_all_num_cols(iris) %>%
#'   head()
round_all_num_cols <- function(df, round_digits = 2) {

  # Convert the data frame to a data.table
  setDT(df)

  # Get the names of the numeric columns
  num_cols <- df[, .SD, .SDcols = is.numeric] %>%
    names()

  # Round the numeric columns to the specified number of digits
  df[, (num_cols) := lapply(.SD, round, digits = round_digits), .SDcols = num_cols]

  # Return the data.table
  df
}
